version: "3"

# See docs.getsentry.com/on-premise/server/ for full instructions
x-defaults: &defaults
  restart: unless-stopped
  build:
    context: .
    dockerfile: sentry/Dockerfile
  depends_on:
    - redis
    - postgres
    - memcached
  env_file: .env
  sysctls:
    net.core.somaxconn: 1024 
  environment:
    SENTRY_MEMCACHED_HOST: memcached
    SENTRY_REDIS_HOST: redis
    SENTRY_POSTGRES_HOST: postgres
  volumes:
    - sentry-data:/var/lib/sentry/files


services:
  memcached:
    restart: unless-stopped
    image: memcached:1.5-alpine

  redis:
    restart: unless-stopped
    image: redis:3.2-alpine

  postgres:
    restart: unless-stopped
    image: postgres:9.5
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - sentry-postgres:/var/lib/postgresql/data

  web:
    <<: *defaults
    ports:
      - '9000:9000'

  cron:
    <<: *defaults
    command: run cron

  worker:
    <<: *defaults
    command: run worker

  caddy:
    # image: caddy
    build:
      context: .
      dockerfile: caddy/Dockerfile
    container_name: caddy
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
    sentry-data:
    caddy_data:
    caddy_config:
    sentry-postgres: